[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Port,
    [string]$Example = 'helloworld'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

. (Join-Path $PSScriptRoot '..\setup\common.ps1')

$repoRoot = Get-PibbiRepoRoot
$config = Get-Esp32S3ToolConfig
$watcherRoot = Join-Path $repoRoot $config.WatcherFirmware.Directory
if (-not (Test-Path -LiteralPath $watcherRoot -PathType Container)) {
    throw 'Watcher firmware checkout is missing. Run bootstrap-esp32s3.ps1 first.'
}

$watcherHead = (& git -C $watcherRoot rev-parse HEAD).Trim()
$shortSha = $watcherHead.Substring(0, 12)
$artifactRoot = Join-Path $repoRoot (Join-Path 'artifacts\esp32s3\build' (Join-Path $shortSha $Example))
$buildRoot = Join-Path $artifactRoot 'build'
$manifestPath = Join-Path $artifactRoot 'build-manifest.json'
$flashArgsPath = Join-Path $buildRoot 'flash_args'

foreach ($path in @($manifestPath, $flashArgsPath)) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Required build artifact not found: $path. Run .\tools\esp32s3\build.ps1 -Example $Example first."
    }
}

$manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
if ($manifest.WatcherCommit -ne $watcherHead) {
    throw "Build manifest belongs to Watcher commit $($manifest.WatcherCommit), but current checkout is $watcherHead"
}
if ($manifest.EspIdfCommit -ne $config.EspIdf.Commit) {
    throw "Build manifest ESP-IDF mismatch: $($manifest.EspIdfCommit)"
}

$elfPath = Join-Path $buildRoot $manifest.Elf.Path
$appBinPath = Join-Path $buildRoot $manifest.ApplicationBin.Path
foreach ($pair in @(
    [pscustomobject]@{ Path = $elfPath; Expected = $manifest.Elf.Sha256; Name = 'ELF' },
    [pscustomobject]@{ Path = $appBinPath; Expected = $manifest.ApplicationBin.Sha256; Name = 'application BIN' }
)) {
    if (-not (Test-Path -LiteralPath $pair.Path -PathType Leaf)) {
        throw "$($pair.Name) is missing: $($pair.Path)"
    }
    $actual = (Get-FileHash -LiteralPath $pair.Path -Algorithm SHA256).Hash.ToLowerInvariant()
    if ($actual -ne $pair.Expected) {
        throw "$($pair.Name) hash changed after build. Expected $($pair.Expected), got $actual. Rebuild before flashing."
    }
}

. (Join-Path $repoRoot 'tools\setup\activate-esp32s3.ps1')

# flash_args is generated by ESP-IDF and contains write_flash options plus
# address/file pairs. Expand it ourselves so no build step can occur during flash.
$flashArgs = @()
foreach ($line in Get-Content -LiteralPath $flashArgsPath) {
    $trimmed = $line.Trim()
    if ([string]::IsNullOrWhiteSpace($trimmed)) { continue }
    $flashArgs += @($trimmed -split '\s+')
}
if ($flashArgs.Count -eq 0) {
    throw "flash_args is empty: $flashArgsPath"
}

Push-Location $buildRoot
try {
    & python -m esptool --chip $config.EspIdf.Target --port $Port --before default_reset --after hard_reset write_flash @flashArgs
    if ($LASTEXITCODE -ne 0) {
        throw "esptool flash failed with exit code $LASTEXITCODE"
    }
}
finally {
    Pop-Location
}

$flashRecord = [ordered]@{
    SchemaVersion = 1
    Platform = 'esp32s3'
    Port = $Port
    Example = $Example
    WatcherCommit = $watcherHead
    EspIdfCommit = $config.EspIdf.Commit
    ElfSha256 = $manifest.Elf.Sha256
    ApplicationBinSha256 = $manifest.ApplicationBin.Sha256
    FlashedAtUtc = [DateTime]::UtcNow.ToString('o')
}
$flashRecordPath = Join-Path $artifactRoot 'flash-manifest.json'
$flashRecord | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath $flashRecordPath -Encoding UTF8

Write-Host ''
Write-Host 'Flash complete.'
Write-Host "Port    : $Port"
Write-Host "Manifest: $flashRecordPath"
